[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Nunes-Will", email = "nuneswillroberto@gmail.com"},
]
dependencies = [
    "django>=4.2.2",
    "djangorestframework>=3.14.0",
    "django-cors-headers>=4.0.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
