# Generated by Django 4.1.7 on 2023-03-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
