# Generated by Django 4.1.7 on 2023-06-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0006_livro_categoria_livro_editora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
    ]
